class Dibujo:
	def dibujarHorca(self):
		print("      +------------+  ")
		print("      |            |  ")
		print("      |            |  ")
		print("                   |  ")
		print("                   |  ")
		print("                   |  ")
		print("                   |  ")
		print("                   |  ")
		print("                   |  ")
		print("                  / \ ")
	
	def dibujarCabeza(self):
		print("      +------------+  ")
		print("      |            |  ")
		print("      |            |  ")
		print("      ☺            |  ")
		print("      |            |  ")
		print("                   |  ")
		print("                   |  ")
		print("                   |  ")
		print("                   |  ")
		print("                  / \ ")
		print("Fallaste. Vuelve a intentar.")
		
	def dibujarBrazo1(self):
		print("      +------------+  ")
		print("      |            |  ")
		print("      |            |  ")
		print("      ☺            |  ")
		print("     /|            |  ")
		print("                   |  ")
		print("                   |  ")
		print("                   |  ")
		print("                   |  ")
		print("                  / \ ")
		print("Fallaste. Vuelve a intentar.")
		
	def dibujarBrazo2(self):
		print("      +------------+  ")
		print("      |            |  ")
		print("      |            |  ")
		print("      ☺7           |  ")
		print("     /|            |  ")
		print("                   |  ")
		print("                   | ")
		print("                   |  ")
		print("                   |  ")
		print("                  / \ ")
		print("Fallaste. Vuelve a intentar.")
		
	def dibujarPierna1(self):
		print("      +------------+  ")
		print("      |            |  ")
		print("      |            |  ")
		print("      ☺7           |  ")
		print("     /|            |  ")
		print("     /             |  ")
		print("                   |  ")
		print("                   |  ")
		print("                   |  ")
		print("                  / \ ")
		print("Fallaste. Vuelve a intentar.")
		
	def dibujarPierna2(self):
		print("      +------------+  ")
		print("      |            |  ")
		print("      |            |  ")
		print("      ☺7           |  ")
		print("     /|            |  ")
		print("     / \           |  ")
		print("                   |  ")
		print("                   |  ")
		print("                   |  ")
		print("                  / \ ")
		print("Se acabaron tus intentos. Perdiste.")
		